name: DNCP

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        flavor: [Debug, Release]
    runs-on: ${{ matrix.os }}
    name: Build (${{ matrix.os }}, ${{ matrix.flavor }})
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
        include-prerelease: true

    - name: Build
      run: |
        mkdir artifacts
        cmake -S . -B artifacts -DCMAKE_BUILD_TYPE=${{ matrix.flavor }}
        cmake --build artifacts --config ${{ matrix.flavor }} --target install

    - name: Build And Run Scenario Tests
      run: dotnet test -c ${{ matrix.flavor }}
      working-directory: ./tests/scenario/ComClient

